### ISSUE TITLE
Check your internet connection is visible during initialisation of the screen

### ISSUE THREAD

**Issue by mennovogel** [parley-messaging/android-library#94]
When the ParleyView is loading, for a short period the "chat_notification_offline"-text is visible, also we you are actually online.
I can only reproduce this in our own app, not in the demo app, but it looks like a bug from the Parley SDK as this text is rendered by the ParleyView.
Also see the screenshot and the video (play the video at a slow speed or frame by frame to see it).
<img width="426" alt="Image" src="https://github.com/user-attachments/assets/f6949faf-cb78-4d89-bd9a-040e72441e17" />

https://github.com/user-attachments/assets/142e3207-64a2-4438-a6bd-c6b72e18a491

**Comment by alexkok** [comment]
Should be fixed in [3.13.0](https://github.com/parley-messaging/android-library/releases/tag/3.13.0) 🚀 
Feel free to let us know or reopen if not 👍

**Comment by mennovogel** [comment]
This issue does not seem to be fixed, I still see the frame when loading the screen after updating to 3.13.0.

https://github.com/user-attachments/assets/4d2fafae-d303-486d-bfb9-ce6b4e8f8f6f
